config/routes.rb
Rails.application.routes.draw do

  post '/users(.:format)', to: 'users#create'
  devise_for :users
  resources :users do
    resources :accesses
  end
  resources :elo_users
  resources :user_informations
  resources :elo_usr_errs

  get '/charts',  to: 'regulations#charts', as: 'charts'
  get '/f440',    to: 'regulations#f440',   as: 'f440'
  get '/f311',    to: 'regulations#f311',   as: 'f311'

  root 'regulations#dashboards'
end

app/models/elo_user.rb
class EloUser < ApplicationRecord
  establish_connection :elodb_mssql

  self.primary_key = 'USRID'

  paginates_per 19

  has_many :elo_usr_errs, foreign_key: 'USERID', foreign_type: :numeric, primary_key: 'USRID'
  # has_many :elo_usr_protocol, -> { where('TIME_ > ?', (Time.now - 2.week).to_date) }, foreign_key: 'USERID', foreign_type: :numeric, primary_key: 'USRID'
  has_many :elo_usr_protocol, foreign_key: 'USERID', foreign_type: :numeric, primary_key: 'USRID'
  has_many :elo_user_jobs, foreign_key: 'USERID', foreign_type: :numeric, primary_key: 'USRID'
  has_many :inactive_users, -> { where(JOBID: -1, DOSTUP: 1) }, foreign_key: 'USERID', primary_key: 'USRID', class_name: 'EloUserJob'

  default_scope { order(USRID: :desc) }

  def id
    self.USRID.to_i
  end

  def login
    self.USRNAME
  end

  def email
    user_information = UserInformation.where("UNICODE = ?", '$user$' + self.id.to_s)
    return user_information.where("CODE = '$execmail$'")[0].nil? ? "" : user_information.where("CODE = '$execmail$'")[0].VOL
  end

  def name
    user_information = UserInformation.where("UNICODE = ?", '$user$' + self.id.to_s)
    return user_information.where("CODE = '$exec$'")[0].nil? ? "" : user_information.where("CODE = '$exec$'")[0].VOL
  end

  def active?
    self.inactive_users.first.nil?
  end
end

app/controllers/elo_users_controller.rb
class EloUsersController < ApplicationController
  def index
    update_sort(controller_name) if params['sort'].present?
    user = EloUser.all.sort_by_session(session[controller_name])
    @elo_users = user.includes(:inactive_users).page(params[:page])
  end

end

app/views/elo_users/_elo_user.html.haml
%tr
  %td= elo_user.id
  - if elo_user.active?
    %td= link_to elo_user.login, user_information_path(elo_user.id), remote: true
  - else
    %td.warning= elo_user.login
  %td= elo_user.email
  %td= elo_user.name

app/views/elo_users/_elo_user_title.html.haml
%tr
  %th#id
    id
  %th#login
    login
  %th#email
    email

app/views/elo_users/index.html.haml
%div.col-md-6
  %table.table.table-condensed
    %thead
      = render 'elo_user_title'
    %tbody
      = render @elo_users

  %br
  = paginate @elo_users, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"
%div.col-md-6.user-information