config/routes.rb
Rails.application.routes.draw do

  post '/users(.:format)', to: 'users#create'
  devise_for :users
  resources :users do
    resources :accesses
  end
  resources :elo_users
  resources :user_informations
  resources :elo_usr_errs

  get '/charts',  to: 'regulations#charts', as: 'charts'
  get '/f440',    to: 'regulations#f440',   as: 'f440'
  get '/f311',    to: 'regulations#f311',   as: 'f311'

  root 'regulations#dashboards'
end

app/models/user.rb
class User < ApplicationRecord
  establish_connection :fsm_mssql

  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable, :omniauthable, :validatable, :recoverable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :lockable, authentication_keys: [:login]

  has_many  :accesses,  dependent: :delete_all

  def admin?
    self.accesses.find_by(role: 1).present?
  end

  def dashboards?
    self.accesses.find_by(role: 5).present?
  end

  def autorefresh?
    self.accesses.find_by(role: 6).present?
  end

  def charts?
    self.accesses.find_by(role: 8).present?
  end

  def f440?
    self.accesses.find_by(role: 30).present?
  end

  def f311?
    self.accesses.find_by(role: 15).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :set_new_access, only: [:edit]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    update_sort(controller_name) if params['sort'].present?
    user = policy_scope(User).all.sort_by_session(session[controller_name])
    @count = user.count
    @users = user.page(params[:page])
    authorize @users
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path(@user)
    end
  end

  def create
    user = User.create(user_params)
    authorize user
    if user.save
      redirect_to edit_user_path(user)
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def set_new_access
    @access = Access.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.haml
- if @user.errors.any?
  %div#error_explanation
    %h2
      = pluralize(@user.errors.count, "error")
      prohibited this user from being saved:
    %ul
      - @user.errors.full_messages.each do |message|
        %li
          = message

app/views/users/_form_user.html.haml
= form_for @user, html: { class: 'form-horizontal', role: 'form' } do |f|

  %div.form-group
    %label.col-sm-4
    %div.col-sm-8
      = render 'users/errors'

  %div.form-group
    %label.col-sm-4.control-label.some{ for: 'user_login' }
      = :login
    %div.col-sm-8
      = f.text_field :login, autofocus: true, :class => "form-control", :id => "user_login", :type => "groupname"
  %div.form-group
    %label.col-sm-4.control-label.some{ for: 'user_email' }
      = :email
    %div.col-sm-8
      = f.email_field :email, :class => "form-control", :id => "user_email", :type => "groupname"
  %div.form-group
    %label.col-sm-4.control-label.some{ for: 'user_password' }
      = :password
    %div.col-sm-8
      = f.password_field :password, :class => "form-control", :id => "user_password", :type => "groupname", autocomplete: "off"
  %div.form-group
    %label.col-sm-4.control-label.some{ for: 'user_password_confirmation' }
      = :password_confirmation
    %div.col-sm-8
      = f.password_field :password_confirmation, :class => "form-control", :id => "user_password_confirmation", :type => "groupname", autocomplete: "off"
  %div.form-group
    %label.col-sm-4
    %div.col-sm-8
      = f.submit

app/views/users/_title.html.haml
%tr
  %th
    = link_to_sort('login')
    = t('.login')
  %th
    = link_to_sort('email')
    = t('.email')
  %th
    = link_to image_tag('user_plus.png'), new_user_path, class: 'btn-icon', title: 'Добавить пользователя'

app/views/users/_user.html.haml
%tr
  %td
    - if policy(user).edit?
      = link_to user.login, edit_user_path(user)
    - else
      = user.login
  %td
    = user.email
  %td
    = link_to '', user_path(user), class: 'glyphicon glyphicon-remove',method: :delete, data: { confirm: 'Are you sure?' } if policy(user).destroy?

app/views/users/_users_table.html.haml
%thead
  = render 'title'
%tbody
  = render @users

app/views/users/edit.html.haml
%div.col-md-6
  = render 'form_user'
%div.col-md-3
%div.col-md-3.user-access
  = render '/accesses/index'

app/views/users/index.html.haml
%div.row
  %div.col-md-12
    %table.table.table-striped.users-table
      = render 'users/users_table'

= paginate @users, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-sm'

app/views/users/index.js.erb
$('.users-table').html("<%= escape_javascript render 'users/users_table' %>");

app/views/users/new.html.haml
= render 'form_user'