config/routes.rb
Rails.application.routes.draw do

  post '/users(.:format)', to: 'users#create'
  devise_for :users
  resources :users do
    resources :accesses
  end
  resources :elo_users
  resources :user_informations
  resources :elo_usr_errs

  get '/charts',  to: 'regulations#charts', as: 'charts'
  get '/f440',    to: 'regulations#f440',   as: 'f440'
  get '/f311',    to: 'regulations#f311',   as: 'f311'

  root 'regulations#dashboards'
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_user

  after_action :verify_authorized

  def create
    authorize @user
    access = @user.accesses.new(role: params[:role].to_i)
    access.save
    @access = Access.new
  end

  def destroy
    a =  @user.accesses.find(params[:id])
    authorize a
    a.destroy
    @access = Access.new
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_access.html.haml
%div.col-md-1
  = link_to '', user_access_path(access.user, access), class: 'glyphicon glyphicon-remove', method: :delete, remote: true, data: { confirm: 'Are you sure?' } if policy(access).destroy?
%div.col-md-11
  = access.role

app/views/accesses/_index.html.haml
%h1
  Роли пользователя
= form_for [@user, @access], html: { role: 'form' }, remote: true do |n|
  = n.button :submit do
    %i.glyphicon.glyphicon-plus
    Add role
  = n.select_tag :role, options_for_select(Access.roles.map {|k, v| [k.humanize.capitalize, v]})
= render @user.accesses

app/views/accesses/create.js.erb
$('.user-access').html("<%= escape_javascript render '/accesses/index' %>")

app/views/accesses/destroy.js.erb
$('.user-access').html("<%= escape_javascript render '/accesses/index' %>")