config/routes.rb
Rails.application.routes.draw do

  post '/users(.:format)', to: 'users#create'
  devise_for :users
  resources :users do
    resources :accesses
  end
  resources :elo_users
  resources :user_informations
  resources :elo_usr_errs

  get '/charts',  to: 'regulations#charts', as: 'charts'
  get '/f440',    to: 'regulations#f440',   as: 'f440'
  get '/f311',    to: 'regulations#f311',   as: 'f311'

  root 'regulations#dashboards'
end

app/views/layouts/_alert.html.haml
= flash_messages

app/views/layouts/_menu.html.haml
%nav{ class: 'navbar navbar-default navbar-fixed-top', role: 'navigation' }
  %div{ class: 'navbar-header'}
    %button.some{ type: 'button', class: 'navbar-toggle', :'data-toggle' => 'collapse', :'data-target' => '#bs-example-navbar-collapse-1' }
      %span{ class: 'sr-only' } Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.some{ href: root_path }
      %span.glyphicon.glyphicon-home

  %div{ class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
    %ul.some{ class: 'nav navbar-nav'}
      - if user_signed_in?
        - if current_user.charts?
          = menu_item('Графики', charts_path, 'charts.png')
        - if current_user.dashboards?
          = menu_item('Ошибки ПТКПСД', elo_usr_errs_path, 'err.png')
        - if current_user.admin?
          = menu_item('Пользователи', users_path, 'users.png')
          = menu_item('Пользователи ПТКПСД', elo_users_path)
        - if current_user.f440?
          = menu_item('440 Положение', f440_path)
        - if current_user.f311?
          = menu_item('311 Положение', f311_path)

    %ul{ class: 'nav navbar-nav navbar-right' }
      - if user_signed_in?
        %li.dropdown
          %a{ href: '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown' }
            = current_user.login
            -#%strong.glyphicon.glyphicon-chevron-down
            %span.glyphicon.glyphicon-collapse-down
          %ul.dropdown-menu
            %li
              = link_to t('EditUser'), edit_user_registration_path
            %li
              = link_to t('Logout'), destroy_user_session_path, method: :delete
      - else
        %li
          = link_to t('LogIn'), new_user_session_path

app/views/layouts/application.html.haml
%html
  %head
    %title Монитор
    = favicon_link_tag 'logo.ico'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

  %body
    %div.container-fluid.main-frame
      = render 'layouts/menu'
      %div.col-md-12.alert-message
        = render 'layouts/alert'
      %div.col-md-12
        = yield